version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: movies
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./movies.sql:/docker-entrypoint-initdb.d/movies.sql
    image: "${DOCKER_USERNAME}/postgres-db:latest"  # Image tag
    

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: movies-app
    ports:
      - "5173:5173"
    environment:
      DATABASE_URL: postgres://postgres:docker@postgres:5432/movies
    depends_on:
      - postgres
    image: "${DOCKER_USERNAME}/my-app:latest"  # Image tag
    

volumes:
  db_data:
