name: CI - Build and Deploy

on:
  push:
    branches:
      - GithubActionConfig # Trigger on push
  pull_request:
    branches:
      - GithubActionConfig  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Set up Docker environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG="${{ github.sha }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG="${{ github.sha }}"
          fi
          docker-compose -f docker-compose.yml build

      - name: Tag Docker images
        run: |
          docker tag my-app:latest "${{ secrets.DOCKER_USERNAME }}/my-app:${TAG}"
          docker tag postgres-db:latest "${{ secrets.DOCKER_USERNAME }}/postgres-db:${TAG}"


       - name: Push Docker images
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/my-app:${TAG}"
          docker push "${{ secrets.DOCKER_USERNAME }}/postgres-db:${TAG}"

      - name: Logout from Docker Hub
        run: docker logout
