name: CI - Build and Deploy

on:
  push:
    branches:
      - GithubActionConfig # Trigger on push
  pull_request:
    branches:
      - GithubActionConfig  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Set up Docker environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and tag Docker images
          run: |
            if [[ "${{ github.event_name }}" == "push" ]]; then
              # Tag to use for a direct push to main
              TAG="${{ github.sha }}"
            elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
              # Tag with commit SHA for PRs
              TAG="${{ github.sha }}"
            fi
            docker-compose -f docker-compose.yml build
            docker tag my-app:latest my-app:$TAG
        
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push
      - name: Logout from Docker Hub